database:
  host: localhost
  port: 5432
  user: amazon_analyst
  password: amazon_analyst_2024
  database: amazon_analyst
  sslmode: prefer
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_pre_ping: true
  pool_recycle: 3600
api:
  base_url: https://api.saihu-erp.com
  timeout: 60
  retry_count: 3
  retry_delay: 1
sync:
  batch_size: 500
  max_history_days: 30
  enable_validation: true
  parallel_workers: 4
